title: MagnetoMagic # your name (or website title) here
logo: "/images/MagnetoMagicNewLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my GitHub Portfolio! My name is Chase Kile, I am a 2D Digital Artist and 3D Modeler. 
  I have some minor programming experience in C# and you can check out
  my showcase of programming projects here. Thank you so much for coming to check out my portfolio.
   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
